INSERT INTO teatro.tsa_plantilla_correo
(id_plantilla_correo, nombre, asunto, descripcion1, descripcion2, descripcion3, imagen, enlace_redes_sociales, telefono, direccion, estado, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion)
VALUES(1, 'Reinicio Contraseña', 'Reinicio Contraseña', 'Recibimos tu solicitud de reinicio de contraseña. Para continuar con el proceso, da clic en el siguiente enlace:', '(CODIGO)', 'Si no has solicitado un reinicio de contraseña, ninguna acción será requerida.', 'ReinicioContrasena-01', 'https://es-https://es-la.facebook.com/TeatroSanchezAguilar/;https://www.instagram.com/teatrosancheza/;https://twitter.com/teatrosancheza;www.teatrosanchezaguilar.org', '0960638248 - 042097447', 'Av. Rio Esmeraldas, Samborondón, 092301', 'S', '2022-03-10 00:00:00.000', 'amendoza', NULL, NULL);
INSERT INTO teatro.tsa_plantilla_correo
(id_plantilla_correo, nombre, asunto, descripcion1, descripcion2, descripcion3, imagen, enlace_redes_sociales, telefono, direccion, estado, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion)
VALUES(2, 'Bienvenido', 'Bienvenido', '<h1 style="font-size:24px;margin:0 0 20px 0;font-family:Arial,sans-serif;">bienvenido al Teatro Sánchez Aguilar</h1>Gracias por crear una cuenta con nosotros. Da clic en el siguiente enlace para disfrutar de todos los beneficios que te esperan.', '(CODIGO)', 'Para realizar cambios en la cuenta en cualquier momento, inicia sesión en el portal', 'Bienvenido-01', 'https://es-https://es-la.facebook.com/TeatroSanchezAguilar/;https://www.instagram.com/teatrosancheza/;https://twitter.com/teatrosancheza;www.teatrosanchezaguilar.org', '0960638248 - 042097447', 'Av. Rio Esmeraldas, Samborondón, 092301', 'S', '2022-03-10 00:00:00.000', 'amendoza', NULL, NULL);
INSERT INTO teatro.tsa_plantilla_correo
(id_plantilla_correo, nombre, asunto, descripcion1, descripcion2, descripcion3, imagen, enlace_redes_sociales, telefono, direccion, estado, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion)
VALUES(3, 'Compra de Boleto', 'Compra de Boleto', 'Todo listo para que disfrutes de la función. <br/> Presenta el siguiente código QR en el ingreso a la sala.', 'CODIGO QR', 'Este código puede ser transferido, presentado desde el celular o impreso.<br/> Recuerda llegar 15 minutos antes. <br/><br/>
<table><tr><td><b>Nombre de función:</b> </td><td>(NOMBRE)</td> </tr><tr><td> <b>Fecha de función:</b>  </td><td>(FECHA)</td></tr><tr><td> <b>Hora de función:</b>  </td><td>(HORA)</td></tr><tr><td> <b>Duración de función:</b>  </td><td>(DURACION)</td></tr><tr><td> <b>Sus asientos:</b>  </td><td>(ASIENTOS)</td></tr></table><br/><br/> <u style="color: #851421;">Términos y condiciones</u> <br/>', 'Compra de boleto-01', 'https://es-https://es-la.facebook.com/TeatroSanchezAguilar/;https://www.instagram.com/teatrosancheza/;https://twitter.com/teatrosancheza;www.teatrosanchezaguilar.org', '0960638248 - 042097447', 'Av. Rio Esmeraldas, Samborondón, 092301', 'S', '2022-03-10 00:00:00.000', 'amendoza', NULL, NULL);
INSERT INTO teatro.tsa_plantilla_correo
(id_plantilla_correo, nombre, asunto, descripcion1, descripcion2, descripcion3, imagen, enlace_redes_sociales, telefono, direccion, estado, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion)
VALUES(4, 'Donacion', 'Donacion', 'Porque cada esfuerzo cuenta, queremos darte las gracias por esta donación con la que aportas a la Fundación Sánchez Aguilar. Te invitamos a conocer cuales sus proyectos, de los que ahora eres parte:</br> http://fundacionsanchezaguilar.org', 'IMAGEN', '¡Sigamos trabajando por la comunidad!', 'Donacion-01', 'https://es-https://es-la.facebook.com/TeatroSanchezAguilar/;https://www.instagram.com/teatrosancheza/;https://twitter.com/teatrosancheza;www.teatrosanchezaguilar.org', '0960638248 - 042097447', 'Av. Rio Esmeraldas, Samborondón, 092301', 'S', '2022-03-10 00:00:00.000', 'amendoza', NULL, NULL);
INSERT INTO teatro.tsa_plantilla_correo
(id_plantilla_correo, nombre, asunto, descripcion1, descripcion2, descripcion3, imagen, enlace_redes_sociales, telefono, direccion, estado, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion)
VALUES(5, 'Cumpleaños', 'Cumpleaños', 'Para nosotros eres demasiado especial, gracias por pertenecer a la comunidad del Teatro Sánchez Aguilar.', 'Esperamos que disfrutes de este día a lo grande, tan grande como el artista que llevas dentro de ti.', 'Te esperamos en Café Vino Bar del teatro los los próximos 30 días para que recibas gratis una copa de sangría o un postre.', 'Cumpleanios-01', 'https://es-https://es-la.facebook.com/TeatroSanchezAguilar/;https://www.instagram.com/teatrosancheza/;https://twitter.com/teatrosancheza;www.teatrosanchezaguilar.org', '0960638248 - 042097447', 'Av. Rio Esmeraldas, Samborondón, 092301', 'S', '2022-01-18 00:00:00.000', 'amendoza', NULL, NULL);
INSERT INTO teatro.tsa_plantilla_correo
(id_plantilla_correo, nombre, asunto, descripcion1, descripcion2, descripcion3, imagen, enlace_redes_sociales, telefono, direccion, estado, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion)
VALUES(6, 'Regalo Para ti', 'Regalo Para ti', 'Sabemos que las primeras veces son importantes, nos alegra haberte recibido por primera vez en el Teatro y queremos regalarte este código de descuento para tu siguiente función:', 'CODIGO DE DESCUENTO', 'Puedes ver la cartelera de programación desde: <strong>www.teatrosanchezaguilar.org</strong> o descargando nuestra <strong>app Teatro Sánchez Aguilar (iOS o Android).</strong> <br/>', 'RegaloParaTi2-01', 'https://es-https://es-https://es-https://es-la.facebook.com/TeatroSanchezAguilar/;https://www.instagram.com/teatrosancheza/;https://twitter.com/teatrosancheza;www.teatrosanchezaguilar.org', '0960638248 - 042097447', 'Av. Rio Esmeraldas, Samborondón, 092301', 'S', '2022-01-18 00:00:00.000', 'amendoza', NULL, NULL);
INSERT INTO teatro.tsa_plantilla_correo
(id_plantilla_correo, nombre, asunto, descripcion1, descripcion2, descripcion3, imagen, enlace_redes_sociales, telefono, direccion, estado, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion)
VALUES(7, 'Boleto de Cortesía', 'Boleto de Cortesía', 'Muchas gracias por su aporte al Teatro y a la </br> Fundación Sanchez Aguilar. Adjunto reciba las </br> cortesías correspondientes, al auspicio acordado con nosotros.</br>
', NULL, NULL, 'Donacion-01', 'https://es-https://es-https://es-la.facebook.com/TeatroSanchezAguilar/;https://www.instagram.com/teatrosancheza/;https://twitter.com/teatrosancheza;www.teatrosanchezaguilar.org', '0960638248 - 042097447', 'Av. Rio Esmeraldas, Samborondón, 092301', 'S', '2022-03-27 00:00:00.000', 'amendoza', NULL, NULL);
