<?php
  //$path_imagen="/teatro-copia/imagenes/";
  //$path_imagen1='/teatro-copia/imagenes/';
  //$path_imagen1='C:\xampp\htdocs\teatro-copia\imagenes/';
  //$path_imagen2='../../../assets/global/images/';
  $path_imagen="/imagenes/";
  $path_imagen1='/var/www/html/imagenes/';
  //$path_imagen1='C:\xampp\htdocs\teatro-copia\imagenes/';
  $path_imagen2='../../../assets/global/images/';
?>